schema_version = "1.0.0"

id = "maya_snap"    
name = "Maya Snapping"
version = "1.0.1"
maintainer = "Eisteed <hello@eisteed.com>"
tagline  = "Snap to vertex / grid (press & release)"
type = "add-on"

blender_version_min = "3.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]